#include "pch.h"
#include "App.xaml.h"
#include "MainWindow.h"
#include "XamlMetaDataProvider.h"

// The implementation of the XAML type info provider generated by C++/WinRT.
#include "XamlTypeInfo.Impl.g.cpp"
#include "XamlTypeInfo.g.cpp"
